== MPD

=== To Do

I think after each reboot that the hardware settings like thhose displayed for `aplay -l` change. Therefore I may need to create a fixed index for, say, the X4 adapter.
See https://notes.maxie.xyz/audio/bit-perfect-hi-res-audio-player-on-linux-with-mpd.html#permanent-index-value-for-the-sound-card-recommended[Permanent index value for the sound card (Recommended)]

To test bit rate, see: https://www.24bit96.com/hifi-music-server/bitperfect-linux-with-mpd.htmlTesting.

=== Links

* https://wiki.archlinux.org/title/Music_Player_Daemon[MPD Guide to all
config options | Arch] ← Excellent introduction
+
* https://mpd.fandom.com/wiki/Configuration[Configuring MPD] ← good
thorough overview. Has link to Linux Audio Explained.
+
* https://www.addictivetips.com/ubuntu-linux-tips/set-up-music-player-daemon-on-linux/[How To Set Up Music Player Daemon On Linux] ← Shows web access to mpd.
* https://notes.maxie.xyz/audio/bit-perfect-hi-res-audio-player-on-linux-with-mpd.html[Bit-Perfect Hi-Res Audio Player on Linux with MPD] ← Good. Shows hardware and mpd
setup. Goes into details.
+
* https://www.24bit96.com/hifi-music-server/bitperfect-linux-with-mpd.html[Bitperfect MPD with ALSA for a Linux Audio PC System] ← Explains how to confirm
bitrate
+
* https://www.youtube.com/watch?v=hksM3xqOU4w[My music setup with mpd, ncmpcpp | Music server in Linux | How to configure mp] ←
+
* https://guillaumeplayground.net/mele-dac-mpd-the-perfect-bit-perfect/[Mele+ DAC + MPD => the perfect bit-perfect setup]

* https://www.youtube.com/watch?v=hW8W6VHskP8[Configure Music Player Daemon and ncmpcpp]
+
* https://www.youtube.com/watch?v=_GLOKTd-8tA&t=75s[Ncmpcpp: The Best MPD Client With The Worst Name]


=== User's Manual

MPD https://mpd.readthedocs.io/en/stable/user.html[User's Manual]


=== General Setup

You can have both a system-wide setup and per-user setups. The system-wide configuration is in `/etc/mpd.conf`, and the user config is in
`~/.config/mpd`/. You can optionally specify a different configure file when starting mpd from the command line:

```bash
$ mpd custom-mpd-conhfig-file
```

If none is given, then `~/.config/mpd/mpd.confg` is used.

MPD’s settings are explained on the
https://wiki.archlinux.org/title/Music_Player_Daemon#Audio_configuration[Arch website]. You can begin with the example settings file:

```bash
$ mkdir ~/.config/mpd

$ cp /usr/share/doc/mpd/mpdconf.example ~/.config/mpd/mpd.conf
```

If playlists are enabled in the configuration, the specified playlist
directory must be created:

```bash
$ mkdir ~/.config/mpd/playlists
```

=== Bit-perfect MPD Configuration Utility

The https://gitlab.com/sonida/mpd-configure[mpd-configure] tool creates
a MPD configuration optimized for
https://www.musicpd.org/doc/user/advanced_usage.html#bit_perfect[bit
perfect] audio playback, without any resampling or conversion, using the
ALSA interface hardware address (hw:x,y).

The *mpd-configure* script requires the *alsa-capabilities* script to be
in ./helpers.

NOTE: The alsa-capabilites bash script should not be independently
installed. See the comments by Quex Quex at
https://gitlab.com/sonida/mpd-configure/-/issues/39). Install it this
way:

```bash
$ git clone git@gitlab.com:sonida/mpd-configure.git

$ cd mpd-configure

$ Sgit submodule update --init –recursive
```

=== MPD Forum

<https://github.com/MusicPlayerDaemon/MPD/discussions>
