:stylesheet: /home/kurt/asciidoc-skins/css/material-green.css

= MPD and Bit-Perfect Audio Setup

== Testing Bit Rate of Current Configuration

To test the bit rate, you can do `sudo cat /proc/asound/card0/pcm0p/sub0/hw_params`, if `card0` is your sound card; or `sudo cat /proc/asound/card1/pcm0p/sub0/hw_params` if `card1` is your sound card.

== MPD User's Manual

MPD https://mpd.readthedocs.io/en/stable/user.html[User's Manual]

== General Setup

=== Default Config File Locations

You can have both a system-wide setup and per-user setups. The system-wide configuration is `/etc/mpd.conf`, and the user config is `~/.config/mpd`/. You can optionally specify a different configure file when starting mpd from the command line:

```bash
$ mpd custom-mpd-config-file
```

If none is given, then `~/.config/mpd/mpd.confg` is used.

=== The Example Config File

A good overview of MPD’s settings is available on the
https://wiki.archlinux.org/title/Music_Player_Daemon#Audio_configuration[Arch website]. You can start with the example config settings file:

```bash
$ mkdir ~/.config/mpd

$ cp /usr/share/doc/mpd/mpdconf.example ~/.config/mpd/mpd.conf
```

=== Playlists Directory

If playlists are enabled in the configuration, the specified playlist directory must be created:

```bash
$ mkdir ~/.config/mpd/playlists
```

=== Bit-perfect MPD Configuration Utility

The https://gitlab.com/sonida/mpd-configure[mpd-configure] tool creates a MPD configuration optimized for
https://www.musicpd.org/doc/user/advanced_usage.html#bit_perfect[bit perfect] audio playback, without any resampling or conversion, using the ALSA interface hardware address 'hw:x,y`.

The `mpd-configure` script requires the `alsa-capabilities` script to be
in `./helpers`.

NOTE: The `alsa-capabilites` bash script should not be independently
installed. See the comments by Quex Quex at
https://gitlab.com/sonida/mpd-configure/-/issues/39). Install it this
way:

```bash
$ git clone git@gitlab.com:sonida/mpd-configure.git

$ cd mpd-configure

$ Sgit submodule update --init –recursive
```

=== Creating a Permanent Index for the Sound Card

The steps given in https://notes.maxie.xyz/audio/bit-perfect-hi-res-audio-player-on-linux-with-mpd.html#permanent-index-value-for-the-sound-card-recommended[permanent index value for the sound card] section of
https://notes.maxie.xyz/audio/bit-perfect-hi-res-audio-player-on-linux-with-mpd.html[Bit-Perfect Hi-Res Audio Player on Linux with MPD] didn't work for me.

But this Arch forum thread tip https://bbs.archlinux.org/viewtopic.php?id=282767 by *Forum Moderator* does supposedly work:

Note: When doing `lsusb`, the first **id** is the vendor id or *vid* and the second id is the product id or **pid**. 

```bash
options snd_usb_audio vid=$VIDOFMAIN$,$VIDOFWEBCAM$ pid=$PIDOFMAIN$,$PIDOFWEBCAM$ index=-1,-2
options snd_hda_intel index=-2,-2
```

He alternately suggested this technique:

```bash
defaults.pcm.!card "Device"; # The override operation mode is necessary here, because of
defaults.ctl.!card "Device"; # different value types.
```

See also:

* https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#Set_the_default_sound_card
* https://alsa.opensrc.org/MultipleCards#The_newer_.22slots.3D.22_method

=== Configuring Client Connections and Inputs

todo: Read the overview articles below.

And read about client connections config see; file:///usr/share/doc/mpd/html/user.html#client-connections


==== Sidebar: How to share files between a Linux and Windows computer

https://www.computerhope.com/issues/ch001636.htm[How to share files between a Linux and Windows computer]

==== MPD Setup and Usage Links

* file:///usr/share/doc/mpd/html/user.html[MPD User Manual]

* https://mpd.fandom.com/wiki/Configuration[Configuring MPD] ← good thorough overview. Has link to Linux Audio Explained.

* https://www.addictivetips.com/ubuntu-linux-tips/set-up-music-player-daemon-on-linux/[How To Set Up Music Player Daemon On Linux] ← Shows web access to mpd.

* https://notes.maxie.xyz/audio/bit-perfect-hi-res-audio-player-on-linux-with-mpd.html[Bit-Perfect Hi-Res Audio Player on Linux with MPD] ← Good. Shows hardware and mpd
setup. Goes into details.
+
* https://www.24bit96.com/hifi-music-server/bitperfect-linux-with-mpd.html[Bitperfect MPD with ALSA for a Linux Audio PC System] ← Explains how to confirm bitrate
* https://guillaumeplayground.net/mele-dac-mpd-the-perfect-bit-perfect/[Mele+ DAC + MPD => the perfect bit-perfect setup]

* https://wiki.archlinux.org/title/Music_Player_Daemon[MPD Guide to all config options | Arch] ← Excellent introduction


=== MPD Clients

https://mpd.fandom.com/wiki/Clients[List of Clients] from the MPD website.

* http://ompd.pl/[O!MPD] is a PHP-base client.
* https://www.youtube.com/watch?v=hW8W6VHskP8[Configure Music Player Daemon and ncmpcpp]
* https://www.youtube.com/watch?v=_GLOKTd-8tA&t=75s[Ncmpcpp: The Best MPD Client With The Worst Name]

=== Ncmpcpp

Copy default configuration:

```bash
$ cp /usr/share/doc/ncmpcpp/config ~/.config/ncmpcpp/
```

=== MPD Forum

<https://github.com/MusicPlayerDaemon/MPD/discussions>
